### ISSUE TITLE
DbCommandExecuteReaderTracerFactory throws NullReferenceException

### ISSUE THREAD

**Issue by htoma** [newrelic/nuget-azure-web-sites#4]
System.Data v4.0.30319

```
NewRelic DEBUG: Error creating tracer, factory name: NewRelic.Agent.Core.Tracer.Factories.Sql.DbCommandExecuteReaderTracerFactory, error: System.NullReferenceException: Object reference not set to an instance of an object.
   at NewRelic.Agent.Core.Tracer.Factories.Sql.SqlCommandTracer.CreateDbCommandTracer(IConfiguration configuration, ITransaction transaction, ClassMethodSignature signature, IDbCommand sqlCommand)
   at NewRelic.Agent.Core.Tracer.Factories.Sql.DbCommandExecuteReaderTracerFactory.GetTracer(IConfiguration configuration, ITransaction transaction, ClassMethodSignature sig, Object command, Object[] args)
   at NewRelic.Agent.Core.Tracer.TracerService.GetTracerFromTracerService(String tracerFactoryName, ClassMethodSignature signature, Object invocationTarget, Object[] args, UInt32 tracerArguments)
```

**Comment by djaffinito** [comment]
Hi @htoma - I created a support ticket for you and will contact you from there.
